avg/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from core import views
import pleio_auth


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^subsites/add', views.add_subsite, name='add_subsite'),
    url(r'^terms/(?P<terms_type>\w+)/$', views.terms, name='terms'),
    url(r'^auth/', include('pleio_auth.urls')),
    url(r'^admin/login/', pleio_auth.views.login, name='admin_login'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from pleio_auth.models import User

class Subsite(models.Model):
    name = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

class SignedAgreement(models.Model):
    subsite = models.ManyToManyField(Subsite, related_name='signed_agreement')
    in_name_of_processing_terms = models.CharField(max_length=150, blank=True)
    accepted_processing_terms = models.BooleanField(default=False, blank=True)
    in_name_of_user_terms = models.CharField(max_length=150, blank=True)
    accepted_user_terms = models.BooleanField(default=False, blank=True)
    version = models.CharField(max_length=10)
    organisation = models.CharField(max_length=150)
    signed_by = models.ForeignKey(User, related_name='signed_agreements', on_delete=models.CASCADE)
    signed_on = models.DateTimeField(auto_now_add=True)

core/forms.py
from django.forms import ModelForm, ModelChoiceField, ModelMultipleChoiceField, BooleanField, CheckboxInput, TextInput, SelectMultiple, ValidationError
from .models import SignedAgreement, Subsite

class SubsiteForm(ModelForm):
    class Meta:
        model = Subsite
        fields = ['name', ]

        labels = {
            'name': 'Naam subsite* (link)',
        }

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
        }

class SignedAgreementForm(ModelForm):

    class Meta:
        model = SignedAgreement
        fields = ['subsite', 'signed_by', 'in_name_of_processing_terms', 'accepted_processing_terms',
                  'in_name_of_user_terms', 'accepted_user_terms', 'organisation']

        labels = {
            'organisation': 'Organisatie*',
            'in_name_of_processing_terms': 'Akkoord namens verantwoordelijke Functionaris Gegevensbescherming (vul naam in)*',
            'in_name_of_user_terms': 'Akkoord namens verantwoordelijke manager/bestuurder (vul naam in)*',
            'signed_by': 'Naam: ',
        }

        widgets = {
            'organisation': TextInput(attrs={'class': 'form-control'}),
            'in_name_of_processing_terms': TextInput(attrs={'class': 'form-control'}),
            'in_name_of_user_terms': TextInput(attrs={'class': 'form-control'}),
            'signed_by': TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
        }

    subsite = ModelMultipleChoiceField(
        required=True,
        queryset=Subsite.objects.all().exclude(signed_agreement__accepted_processing_terms=True, signed_agreement__accepted_user_terms=True).order_by('name'),
        label='Deelsite* (houd CTRL ingedrukt om meerdere te selecteren)',
        widget=SelectMultiple(attrs={'class': 'form-control', 'size': 10})
    )

    accepted_processing_terms = BooleanField(
        required=False,
        widget=CheckboxInput(attrs={'class': 'form-check-input'}),
        label='Ja, ik accepteer de verwerkersovereenkomst'
    )

    accepted_user_terms = BooleanField(
        required=False,
        widget=CheckboxInput(attrs={'class': 'form-check-input'}),
        label='Ja, ik accepteer de gebruikersovereenkomst'
    )

    def clean(self):
        cleaned_data = super(SignedAgreementForm, self).clean()

        in_name_of_processing_terms = cleaned_data.get("in_name_of_processing_terms")
        accepted_processing_terms = cleaned_data.get("accepted_processing_terms")
        in_name_of_user_terms = cleaned_data.get("in_name_of_user_terms")
        accepted_user_terms = cleaned_data.get("accepted_user_terms")

        if not accepted_processing_terms and not accepted_user_terms:
            msg = "Accepteer Verwerkersovereenkomst en/of Gebruikersovereenkomst"
            self.add_error('accepted_processing_terms', msg)
            self.add_error('accepted_user_terms', msg)

        if accepted_processing_terms and in_name_of_processing_terms.strip() == "":
            msg = "Wanneer Verwerkersovereenkomst is geaccepteerd, dan is naam Functionaris Gegevensbescherming verplicht."
            self.add_error('in_name_of_processing_terms', msg)
        if accepted_user_terms and in_name_of_user_terms.strip() == "":
            msg = "Wanneer Gebruikersovereenkomst is geaccepteerd, dan is naam manager/bestuurder verplicht."
            self.add_error('in_name_of_user_terms', msg)

core/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.contrib import messages
from .models import Subsite, SignedAgreement
from .forms import SubsiteForm, SignedAgreementForm

@login_required
def add_subsite(request):
    if request.POST:
        form = SubsiteForm(request.POST)
        if form.is_valid():
            subsite = form.save(commit=False)
            subsite.save()
            messages.add_message(request, messages.INFO, 'De subsite {} is toegevoegd.'.format(subsite.name))

            return redirect('/subsites/add')
    else:
        form = SubsiteForm()

    return render(request, 'add_subsite.html', {
        'form': form
    })

@login_required
def index(request):
    if request.POST:
        form = SignedAgreementForm(request.POST)
        form.fields.pop('signed_by')
        if form.is_valid():
            signed_agreement = form.save(commit=False)
            signed_agreement.signed_by = request.user
            signed_agreement.version = '2.0'
            signed_agreement.save()
            form.save_m2m()
            messages.add_message(request, messages.INFO, 'De overeenkomst is ondertekend.')

            return redirect('/')
    else:
        form = SignedAgreementForm(initial={'signed_by': request.user.name})

    return render(request, 'index.html', {
        'form': form,
        'user_signed_agreements': SignedAgreement.objects.filter(signed_by=request.user),
        'user': request.user
    })

@login_required
def terms(request, terms_type):
    if terms_type in ['user', 'processing']:
        return render(request, 'terms/{}.html'.format(terms_type))
    raise Http404('Could not find this type of terms.')

core/templates/add_subsite.html
{% extends "base.html" %}

{% block content %}
	<h2>Subsite toevoegen</h2>
	<form action="/subsites/add" method="post" enctype="multipart/form-data" novalidate>
		{% csrf_token %}

		<div class="form-group">
			<label for="id_name">{{form.name.label}}</label>
			{{form.name.errors}}
			{{form.name}}
        </div>
        
		<button class="btn btn-primary" type="submit">Toevoegen</button>
		<a href="/" class="btn btn-secondary" role="button" aria-pressed="true">Terug</a>
    </form>
{% endblock %}

core/templates/base.html
{% load static %}
<!doctype html>
<html lang="nl">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Overeenkomsten accepteren</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy"
    crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
    crossorigin="anonymous">
    <link rel="stylesheet" href="./static/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="./static/css/style.css">

</head>

<body>
    {% if user.is_authenticated %}
        {% include 'partials/nav.html' %}
    {% endif %}

    {% if show_sidebar %}
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="container mt-4 break-word">
                        {% block sidebar %}{% endblock %}
                    </div>
                </nav>
                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                    <div class="mt-4">
    {% else %}
        <main role="main">
            <div class="container mt-4">
    {% endif %}

            {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
            {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
            {% endfor %}

            {% block content %}{% endblock %}

    {% if show_sidebar %}
                </div>
            </main>
        </div>
    {% else %}
            </div>
        </main>
    {% endif %}

    <script src="//code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
    crossorigin="anonymous"></script>
</body>

</html>

core/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<h2>Accepteer de overeenkomsten voor je deelsite</h2>
	<p>
		Vul het onderstaande formulier in om de overeenkomsten voor je deelsite
		te acceptereren. Staat je deelsite er niet meer tussen? Dan is de overeenkomst
		wellicht al geaccepteerd door iemand anders? Zo niet, voeg dan de deelsite <a href="/subsites/add">hier</a> toe.
	</p>
	<form action="." method="post" class="mt-4 mb-4">
		{% csrf_token %}

		<div class="form-group">
			Naam: {{ user.name }}
		</div>

		<div class="form-group">
            <label for="id_organisation">{{ form.organisation.label }}</label>
			{{ form.organisation }}
			{{ form.organisation.errors }}
		</div>

		<div class="form-group">
			<label for="id_subsite">{{ form.subsite.label }}</label>
			{{ form.subsite }}
			{{ form.subsite.errors }}
		</div>
		<br><br><br>
		<div class="form-group">
		<strong>Verwerkersovereenkomst:</strong>
			<a href="https://support.pleio.nl/cms/view/57979129/contact/57981139" target="_blank">verwerkersovereenkomst</a>
		</div>
		<br>
		<div class="form-group">
            <label for="id_in_name_of_processing_terms">{{ form.in_name_of_processing_terms.label }}</label>
			{{ form.in_name_of_processing_terms }}
			{{ form.in_name_of_processing_terms.errors }}
		</div>

		<div class="form-group form-check">
			{{ form.accepted_processing_terms }}
			<label for="id_accepted_processing_terms">{{ form.accepted_processing_terms.label }}</label>
			{{ form.accepted_processing_terms.errors }}
		</div>

		<br><br><br>
		<div class="form-group">
		<strong>Gebruikersovereenkomst:</strong>
			<a href="https://support.pleio.nl/cms/view/57979129/contact/57981139" target="_blank">gebruikersovereenkomst</a>
		</div>

		<div class="form-group">
            <label for="id_in_name_of_user_terms">{{ form.in_name_of_user_terms.label }}</label>
			{{ form.in_name_of_user_terms }}
			{{ form.in_name_of_user_terms.errors }}
		</div>


		<div class="form-group form-check">
			{{ form.accepted_user_terms }}
			<label class="form-check-label" for="id_accepted_user_terms">{{ form.accepted_user_terms.label }}</label>
			{{ form.accepted_user_terms.errors }}
		</div>
		<br>

		<div class="form-group">
        	<button class="btn btn-primary" type="submit">Opslaan</button>
		</div>

	</form>
	<br><br>
	<h4>Je hebt de volgende overeenkomsten geaccepteerd</h4>

	<div class="table-responsive">
		<table class="table table-hover">
			<tbody>
				{% for agreement in user_signed_agreements %}
					{% for subsite in agreement.subsite.all  %}
						{% if agreement.accepted_processing_terms %}
							<tr>
								<td>{{ subsite.name }}</td>
								<td>versie {{ agreement.version }}</td>
								<td>Verwerkersovereenkomst</td>
								<td>{{ agreement.signed_on }}</td>
							</tr>
						{% endif %}
						{% if agreement.accepted_user_terms %}
							<tr>
								<td>{{ subsite.name }}</td>
								<td>versie {{ agreement.version }}</td>
								<td>Gebruikersovereenkomst</td>
								<td>{{ agreement.signed_on }}</td>
							</tr>
						{% endif %}
					{% empty %}
					<tr>
						<td>Geen</td>
					</tr>
					{% endfor %}
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}